const sections=[
  {id:'about',number:'01',title:'About',kicker:'FOUR FRIENDS. ONE DEEP CRATE.',paragraphs:['Born from years of friendship, music discovery, and trading vinyl, Compas Discoteca is a collective united out of a shared passion for the art of sound. Made up of four seasoned DJs, Ricardo, Albert, Adrian, and Elias, each member brings a distinct style, creating a dynamic fusion that defies categorization.','From soulful tropical rhythms and undiscovered Latin gems to funk, disco, hip-hop, alternative, R&B, and beyond, the group curates a kaleidoscope of sound that celebrates both the familiar and the unexpected.','At its heart, Compas Discoteca is about creating an atmosphere where music discovery and good times reign supreme. You can find us on dance floors, in listening rooms, at private events, clubs, lounges, and beyond.'],images:[['assets/gallery/compas-05.jpg','Compas Discoteca together behind the turntables']]},
  {id:'sound',number:'02',title:'Our Sound',kicker:'FAMILIAR / UNEXPECTED',paragraphs:['Soulful tropical rhythms, undiscovered Latin gems, funk, disco, hip-hop, alternative, R&B, and beyond.'],images:[['assets/gallery/compas-02.jpg','Compas Discoteca sharing a record at the booth'],['assets/gallery/compas-06.jpg','Compas Discoteca spinning a 45']]},
  {id:'events',number:'03',title:'Coming soon',kicker:'FROM LISTENING ROOMS TO DANCE FLOORS',paragraphs:['Coming soon.'],images:[['assets/gallery/compas-05.jpg','Compas Discoteca together behind the turntables']]},
  {id:'contact',number:'04',title:'Contact',kicker:'PUT A RECORD ON',paragraphs:['Bookings, collaborations, discoveries, and all other good ideas. Come find us on Instagram or send a note.'],images:[['assets/gallery/compas-03.jpg','Compas Discoteca selecting records']]},
  {id:'shop',number:'05',title:'Coming soon',kicker:'OBJECTS FROM THE COLLECTIVE',paragraphs:['Coming soon.'],images:[['assets/gallery/compas-01.jpg','Compas Discoteca digging through records together']]}
];
const buttons=[...document.querySelectorAll('.record')];const details=document.querySelector('.details');let active=-1;
function links(section){if(section.id==='contact')return '<div class="detail-links contact-actions"><a href="mailto:info@heartsoundent.com">EMAIL US ↗</a><a href="https://www.instagram.com/compasdiscoteca" target="_blank" rel="noreferrer">FOLLOW ON INSTAGRAM ↗</a></div>';if(section.id==='sound')return '<div class="detail-links sound-links"><a href="https://www.youtube.com/watch?v=5J4N5JqHa6M&list=RD5J4N5JqHa6M&start_radio=1&t=6352s" target="_blank" rel="noreferrer">WATCH SET 01 ↗</a><a href="https://www.youtube.com/watch?v=DJrR73imZdY&list=RDDJrR73imZdY&start_radio=1&t=1071s" target="_blank" rel="noreferrer">WATCH SET 02 ↗</a></div>';if(section.id==='shop')return '<div class="detail-links"><a href="mailto:info@heartsoundent.com?subject=Compas%20Discoteca%20Shop">GET UPDATES ↗</a></div>';return '<button class="next">NEXT RECORD →</button>'}
function openSection(index){if(active===index){closeDetails();return}active=index;const s=sections[index];buttons.forEach((b,i)=>{b.classList.toggle('selected',i===index);b.setAttribute('aria-selected',String(i===index))});details.innerHTML=`<button class="close" aria-label="Close record details">×</button><p class="detail-number">SIDE ${s.number}</p><h2>${s.title}</h2><p class="kicker">${s.kicker}</p><div class="detail-photos">${s.images.map(([src,alt])=>`<img src="${src}" alt="${alt}">`).join('')}</div><div class="detail-copy">${s.paragraphs.map(p=>`<p>${p}</p>`).join('')}</div>${links(s)}`;details.classList.add('open');details.querySelector('.close').onclick=closeDetails;const next=details.querySelector('.next');if(next)next.onclick=()=>openSection((active+1)%sections.length)}
function closeDetails(){active=-1;buttons.forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-selected','false')});details.classList.remove('open')}
buttons.forEach((b,i)=>b.addEventListener('click',()=>openSection(i)));addEventListener('keydown',e=>{if(e.key==='Escape')closeDetails();if(e.key==='ArrowRight')openSection(active<0?0:(active+1)%sections.length);if(e.key==='ArrowLeft')openSection(active<0?sections.length-1:(active-1+sections.length)%sections.length)});
